###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: leaguemanager-redis

    postgres:
      image: postgres:11.1-alpine
      container_name: leaguemanager-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=LeagueManager
      ports:
        - "8769:5432"

    webserver:
      image: nginx:alpine
      container_name: leaguemanager-webserver
      working_dir: /
      volumes:
          - ./leaguemanager/:/var/www/leaguemanager
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8765:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: leaguemanager-php-fpm
      working_dir: /
      volumes:
        - ./leaguemanager/:/var/www/leaguemanager
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

